version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.9.2
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  logstash:
    image: logstash:7.9.2
    restart: always
    command: logstash -f /home/lenovo/Downloads/SPE_PROJ-main/ELK.conf
    ports:
      - '9600:9600'    
  
  kibana:
    image: kibana:7.9.2
    restart: always
    ports:
      - '5601:5601'
    environment:
        - ELASTICSEARCH_URL=http://127.0.0.1:9200


   